### Logistic regression analysis
```{r}
# Convert sample data to a dataframe
sample_data_df_cp_np <- data.frame(ps_RA_cpall_gf_np@sam_data)

sample_data_df_cp_np <- sample_data_df_cp_np %>%
   distinct(VGO3_ID, .keep_all = TRUE)

#### Logistic regression for continuous variables ####
# We conduct logistic regression to determine whether the probability of belonging to a specific cluster increases with higher values of each continuous variable.
# For RF-modelled concentrations, we use a multivariable logistic regression model per exposure agent i.e. cluster1 ~ e.coli + age + gender + season + smoking
# For distance-based variables, we test them all together in one multivariable logistic regression model i.e. cluster1 ~ goats+ cows + pigs + poultry + age + gender + season + smoking


# Since Logistic regression requires sufficient counts in each outcome category to generate reliable and stable parameter estimates, we will exclude some of the clusters with low counts - anything with below 10 counts (out of the 1000 CPs)
# Calculate cluster counts
cluster_counts <- table(sample_data_df_cp_np$cluster)
# Identify clusters with counts >= 10
clusters_to_keep <- names(cluster_counts[cluster_counts >= 10])
# Filter the dataset to retain only rows with clusters in clusters_to_keep
sample_data_df_cp_np <- sample_data_df_cp_np %>%
  filter(cluster %in% clusters_to_keep)

# Define the columns where we want to replace NA values with 0
columns_to_replace_na <- c("KRD_nGoatsWghtDist.3000m.sum_std", 
                           "KRD_nCowsWghtDist.3000m.sum_std", 
                           "KRD_nPoultryWghtDist.3000m.sum_std", 
                           "KRD_nPigsWghtDist.3000m.sum_std")

# Replace NAs with 0 for the specified columns
for (column in columns_to_replace_na) {
  sample_data_df_cp_np[[column]] <- replace_na(sample_data_df_cp_np[[column]], 0)
}

# Initialize an empty data frame to store logistic regression results
logistic_results_df_cp_np_std <- data.frame()

# Define the additional variables for the multivariable model
additional_vars <- c("age", "gender", "smoked_ever", "sampling_season")

# Convert categorical data to factors and set reference levels
sample_data_df_cp_np$gender <- relevel(as.factor(sample_data_df_cp_np$gender), ref = "0") 
sample_data_df_cp_np$smoked_ever <- relevel(as.factor(sample_data_df_cp_np$smoked_ever), ref = "0")  
sample_data_df_cp_np$sampling_season <- relevel(as.factor(sample_data_df_cp_np$sampling_season), ref = "Summer")  

# Set continuous variables based on columns_to_replace_na
continuous_vars <- columns_to_replace_na

# Loop through each cluster
for (clust in unique(sample_data_df_cp_np$cluster)) {
  # Create a binary outcome for each cluster (1 if sample is in the cluster, 0 otherwise)
  sample_data_df_cp_np$in_cluster <- ifelse(sample_data_df_cp_np$cluster == clust, 1, 0)
  # Fit the multivariable logistic regression model for the continuous variables
  formula_multivariable <- as.formula(paste("in_cluster ~", paste(c(continuous_vars, additional_vars), collapse = " + ")))
  model_multivariable <- glm(formula_multivariable, 
                             data = sample_data_df_cp_np, 
                             family = binomial)
  # Extract summary statistics
  summary_stats <- as.data.frame(summary(model_multivariable)$coefficients)
  # Add cluster and variable names for clarity
  summary_stats$Cluster <- clust
  summary_stats$Variable <- rownames(summary_stats)
  # Append to the results data frame
  logistic_results_df_cp_np_std <- rbind(logistic_results_df_cp_np_std, summary_stats)

    # Run separate models for each RF predictor
  for (rf_var in c("EU_ANNUALAVG_PM10_2020_std", "ecoli_RF_preds_std", "staph_RF_preds_std", "tetw_RF_preds_std", "meca_RF_preds_std")) {
    rf_formula <- as.formula(paste("in_cluster ~", rf_var, "+ age + gender + smoked_ever + sampling_season"))
    
    model_rf <- glm(rf_formula, 
                    data = sample_data_df_cp_np, 
                    family = binomial)
    
    # Extract summary statistics
    rf_summary_stats <- as.data.frame(summary(model_rf)$coefficients)
    # Add cluster and variable names for clarity
    rf_summary_stats$Cluster <- clust
    rf_summary_stats$Variable <- rf_var
    # Append to the results data frame
    logistic_results_df_cp_np_std <- rbind(logistic_results_df_cp_np_std, rf_summary_stats)
  }
}



# Rearrange columns to show Cluster and Variable first (optional)
logistic_results_df_cp_np_std <- logistic_results_df_cp_np_std %>%
  select(Cluster, Variable, everything())
# Print save the results
print(logistic_results_df_cp_np_std)
# Add a new column "Covariate" to logistic_results_df_cp_np by removing numbers from the end of each Variable name
logistic_results_df_cp_np_std$Covariate <- gsub("[0-9]+$", "", rownames(logistic_results_df_cp_np_std)) # This removes the number at the end of the variable - but also removes the 2020 from the EU_ANNUALAVG_PM10_ variable - so remove this from the next part to make sure it's included in the final dataframe

# Filter results and retain only rows of interest, then arrange columns for readability
# Define the covariates to filter by
covariates_to_keep <- c("EU_ANNUALAVG_PM10_2020_std", "ecoli_RF_preds_std", "staph_RF_preds_std", "tetw_RF_preds_std", "meca_RF_preds_std",
                        "KRD_nGoatsWghtDist.3000m.sum_std", "KRD_nCowsWghtDist.3000m.sum_std",
                        "KRD_nPoultryWghtDist.3000m.sum_std", "KRD_nPigsWghtDist.3000m.sum_std") 

# Filter the dataset to include only the specified covariates
filtered_covariates_df_np_std <- logistic_results_df_cp_np_std %>%
  filter(Covariate %in% covariates_to_keep)
# Apply the BH adjustment locally to the filtered covariates
filtered_covariates_df_np_std$BH_adjusted_pvalue <- p.adjust(filtered_covariates_df_np_std$`Pr(>|z|)`, method = "BH")
# Save as .csv
write.csv(filtered_covariates_df_np_std, "../Output/Cluster_analysis/CP_NP/Logistic_regression_results_cp_np_standardised.csv")

# # Test BH-adjustment on all covariates in the models
# # Apply the BH adjustment globally across all p-values in the full dataset
# logistic_results_df_cp_np$BH_adjusted_pvalue_global <- p.adjust(logistic_results_df_cp_np$`Pr(>|z|)`, method = "BH")


# This logistic regression analysis Without a reference category, means that we get estimates for the "odds ratio" for each cluster in relation to the rest of the clusters, rather than a direct comparison between a chosen "reference" cluster and all others.
# Without a reference group, the odds ratios in these models represent the likelihood of being in a given cluster vs. any other cluster combined, which can be harder to interpret in context


### Heatmap of odds ratios
# Present the Odds ratio instead of the estimate - this tells us how the odds of belonging to a specific cluster change with each unit increase in the predictor variable. 
# only include columns of interest
log_regr_results_cp_np_std <- filtered_covariates_df_np_std %>%
  select(Cluster, Variable, Estimate, BH_adjusted_pvalue, `Std. Error`)

# Calculate Odds Ratios and Confidence Intervals
log_regr_results_cp_np_std <- log_regr_results_cp_np_std %>%
  mutate(
    OR = exp(Estimate),
    Lower_CI = exp(Estimate - 1.96 * `Std. Error`),
    Upper_CI = exp(Estimate + 1.96 * `Std. Error`)
  )

# Reorder the variables for the plot
log_regr_results_cp_np_std$Variable <- factor(log_regr_results_cp_np_std$Variable,
  levels = c("KRD_nCowsWghtDist.3000m.sum_std","KRD_nPoultryWghtDist.3000m.sum_std","KRD_nGoatsWghtDist.3000m.sum_std","KRD_nPigsWghtDist.3000m.sum_std","meca_RF_preds_std","tetw_RF_preds_std","staph_RF_preds_std","ecoli_RF_preds_std", "EU_ANNUALAVG_PM10_2020_std"))

log_regr_results_cp_np_std <- log_regr_results_cp_np_std %>%
  mutate(Variable = dplyr::recode(Variable,
    "EU_ANNUALAVG_PM10_2020" = "Endotoxin exposure",
    "ecoli_RF_preds" = "E. coli exposure",
    "staph_RF_preds" = "Staph spp. exposure",
    "tetw_RF_preds" = "tetW exposure",
    "meca_RF_preds" = "mecA exposure",
    "KRD_nPigsWghtDist.3000m.sum" = "Pigs",
    "KRD_nGoatsWghtDist.3000m.sum" = "Goats",
    "KRD_nPoultryWghtDist.3000m.sum" = "Chickens",
    "KRD_nCowsWghtDist.3000m.sum" = "Cattle"
  ))


log_regr_results_cp_np_std <- log_regr_results_cp_np_std %>%
  mutate(Significance = case_when(
    BH_adjusted_pvalue < 0.1 ~ "*",
    TRUE ~ ""
  ))


# Create heatmap data as before
heatmap_data_cp_np_std <- log_regr_results_cp_np_std %>%
  select(Variable, Cluster, OR, Significance) %>%
  dcast(Variable ~ Cluster, value.var = "OR")  # Reshape data for heatmap

# Convert to long format for ggplot
heatmap_long_cp_np_std <- melt(heatmap_data_cp_np_std, id.vars = "Variable", variable.name = "Cluster", value.name = "OR")

# Merge significance markers back into the long format dataframe
heatmap_long_cp_np_std <- heatmap_long_cp_np_std %>%
  left_join(log_regr_results_cp_np %>% select(Variable, Cluster, Significance), by = c("Variable", "Cluster"))


# Reorder Variable factor levels
heatmap_long_cp_np_std$Variable <- factor(
  heatmap_long_cp_np_std$Variable,
  levels = c(
    "Endotoxin exposure",
    "E. coli exposure",
    "Staph spp. exposure",
    "tetW exposure",
    "mecA exposure",
    "Pigs",
    "Goats",
    "Chickens",
    "Cattle"
  )
)

# Flip plot 
heatmap_residential_expo_cp_np_flip_std <- ggplot(heatmap_long_cp_np_std, aes(x = Variable, y = Cluster, fill = OR)) +
  geom_tile(color = "white") +
  scale_fill_gradient2(
    low = carto_pal(7, "Geyser")[1], 
    mid = carto_pal(7, "Geyser")[4], 
    high = carto_pal(7, "Geyser")[7], 
    midpoint = 1,
    name = "Odds Ratio"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size =14),  # Use element_text for line breaks
    plot.title = element_text(hjust = 0.5),
    axis.text.y = element_text( size =14)  # Regular text for y-axis
  ) +
  geom_text(aes(label = Significance), color = "black", size = 5, vjust = 0.5) 

heatmap_residential_expo_cp_np_flip_std
# Save the heatmap
ggsave("../Output/Cluster_analysis/CP_NP/Residential_livestock_expo_heatmap_flip_std.svg", heatmap_residential_expo_cp_np_flip_std, width = 6, height = 4)
