---
title: "Descriptive statistics"
author: "Beatrice Cornu Hewitt"
date: "`r Sys.time()`"
---

# Packages
```{r}
# List of required packages
library(attachment)
required_packages <- c(
  "dplyr", "table1", "knitr", "kableExtra", "ggpubr", "gtsummary", "microbiomer")
# Install missing packages
install_if_missing(required_packages)
# Load all required packages
lapply(required_packages, library, character.only = TRUE)
```
# Functions
The functions used in this RMarkdown file are stored in "functions.R"
```{r}
source("functions.R")
```

# Data
```{r}
ps_complete <- readRDS("../Output/Phyloseq/ps_complete_new_metadata_RFpreds.Rds")
metadata <- meta_to_df(ps_complete)
metadata$KRD_nCowsWghtDist.3000m.sum
```


Create a visual overview of the samples across the three populations

```{r}
metadata_noblanks <- metadata[!is.na(metadata$population), ]

# Keep only one unique VGO3_ID per niche
metadata_unique <- metadata %>%
  group_by(niche) %>%
  distinct(VGO3_ID, .keep_all = TRUE) %>%
  ungroup()

t <- count(metadata_unique, population, niche) %>% as.data.frame()
t <- subset(t, !is.na(population))

sample_plot <- ggplot(t, aes(x = population, y = n, fill = niche)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("burlywood3", "cadetblue3")) +
  labs(x = "Population", y = "Number of samples", fill = "Sample type") +
  geom_text(position = position_stack(vjust = 0.5), 
            aes(label = n, colour = niche), size = 5) +
  scale_colour_manual(values = c("burlywood4", "cadetblue4")) +
  guides(colour = "none") +
  theme(
    axis.title = element_text(size = 16), # Axis titles
    axis.text = element_text(size = 16), # Axis text
    legend.title = element_text(size = 16), # Legend title
    legend.text = element_text(size = 16)# Legend text
  )

ggsave("../Output/Microbiome_descriptives/sample_plot.svg", sample_plot)


# Plot only for CP and GF 
# Subset data to include only 'CP' and 'GF' populations
t_filtered <- subset(t, population %in% c("CP", "GF"))

# Create the plot with the filtered data
sample_plot_filtered <- ggplot(t_filtered, aes(x = population, y = n, fill = niche)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("burlywood3", "cadetblue3")) +
  labs(x = "Population", y = "Number of samples", fill = "Sample type") +
  geom_text(position = position_stack(vjust = 0.5), 
            aes(label = n, colour = niche), size = 5) +
  scale_colour_manual(values = c("burlywood4", "cadetblue4")) +
  guides(colour = "none") +
  theme(
    axis.title = element_text(size = 16), # Axis titles
    axis.text = element_text(size = 16), # Axis text
    legend.title = element_text(size = 16), # Legend title
    legend.text = element_text(size = 16)  # Legend text
  )

# Display the filtered plot
print(sample_plot_filtered)

ggsave("../Output/Microbiome_descriptives/sample_plot_CPandGFonly.svg", sample_plot_filtered)


```
# Data adjustments
```{r}
# Many of the variables are imported as integer variables when they should actually be character variables
variables_to_factor_part1 <- c("gender", "abroad_lastmth", "animal_contact_lastmth", "cat_contact_lastmth", "dog_contact_lastmth", "rodent_contact_lastmth", "bird_contact_lastmth", "chicken_contact_lastmth", "sheep_contact_lastmth", "cow_contact_lastmth", "pig_contact_lastmth", "horse_contact_lastmth", "pneumonia_lastyr", "acute_resp_infec_lastyr", "covid19", "covid19_vaccine", "antibiotics_lastyr", "antacids_lastyr", "lung_med", "lung_med1_type", "lung_med1_more4hrs", "lung_med1_more8hrs", "lung_med2_type", "lung_med2_more4hrs", "lung_med2_more8hrs", "lung_med3_type", "lung_med3_more4hrs", "lung_med3_more8hrs", "lung_med4_type", "lung_med4_more4hrs", "lung_med4_more8hrs", "lung_med5_type", "lung_med5_more4hrs", "lung_med5_more8hrs", "beta_blockers", "heart_failure_attack_3m", "chest_abdom_surg_3m", "aortic_aneurysm", "cough_blood", "eye_ear_brain_surg_lastmth", "imm_def_med_current", "imm_def_illness_current", "preg_last_trimester", "lungfunc_discom", "breathalyser_diff", "consent", "onlquest_done", "fieldquest_done", "spirometry_done", "serum_done", "OP_blank_done", "NP_blank_done", "NP_blank_ID", "NP_swab_done", "work_less_19hrs", "work_more_19hrs", "manage_house", "unemployed", "student", "disabled", "retired", "voluntarywork", "health_status", "heart_vascu_disorder", "imm_def_illness", "imm_def_med", "diabetes", "wheezing_lastyr", "wheezing_SOB", "wheezing_not_cold", "tight_chest_lastyr", "SOB_lastyr", "cough_lastyr", "SOB_rest_lastyr", "nasal_allergy", "nasal_allergy_Jan", "nasal_allergy_Feb", "nasal_allergy_Mar", "nasal_allergy_Apr", "nasal_allergy_May", "nasal_allergy_Jun", "nasal_allergy_Jul", "nasal_allergy_Aug", "nasal_allergy_Sep", "nasal_allergy_Oct", "nasal_allergy_Nov", "nasal_allergy_Dec", "asthma_ever", "asthma_diag", "asthma_Jan_Feb", "asthma_Mar_Apr", "asthma_May_Jun", "asthma_Jul_Aug", "asthma_Sep_Oct", "asthma_Nov_Dec", "asthma_att_lastyr", "asthma_med", "cough_daily_3mperyr", "phlegm_daily_3mperyr", "COPD_emphysema_diag", "EAA_diag", "cort_inhaler_lastyr", "pneumonia_last3yr", "pneumonia_GP_diag", "pneumonia_antibiotics")
variables_to_factor_part2 <- c("pneumonia_specialist", "pneumonia_specialist_conf", "pneumonia_chest_photo", "pneumonia_conf_photo", "pneumonia_specialist_antibiotics", "pneumonia_hosp", "pneumonia_fever", "pneumonia_dyspnea", "pneumonia_cough", "pneumonia_muscle_pain", "pneumonia_chest_pain", "pneumonia_wheezing", "pneumonia_stomach_pain", "pneumonia_fatigue", "pneumonia_depressed", "flu_vacc", "flu_vacc_duration", "pneumococcal_vacc", "antibiotics_lastyr_oqdata", "antibiotic_month_oqdata", "antibiotic_year_oqdata", "last_antibiotic_used", "covid19_close_contact", "covid19_household", "home_type", "move_plans", "move_no_reason", "move_health", "move_job", "move_house", "move_env", "pets_last5yrs", "cat_last5yrs", "dog_last5yrs", "bird_last5yrs", "small_animals_last5yrs", "rodent_last5yrs", "fish_last5yrs", "turtle_last5yrs", "farmanim_hobby_last5yrs", "pig_last5yrs", "cow_last5yrs", "sheep_last5yrs", "goat_last5yrs", "poultry_last5yrs", "horse_last5yrs", "no_farm_visit_lastyr", "family_farm_visit_lastyr", "job_farm_visit_lastyr", "buy_farm_visit_lastyr", "petting_zoo_visit_lastyr", "other_reason_farm_visit_lastyr", "smoked_ever", "smoke_exp_indoor_freq", "symptom_other", "CRP_test_done", "Saturation_test_done", "lung_disease", "COPD_status", "imm_def", "lung_inhal_med", "antibiotics_lastmth", "dyspnea", "cough", "hypotension", "fever", "pain_breathing", "tachycardia", "tachypnea", "confusion", "lung_med1type", "goat_contact_lastmth", "health_remarks", "lambs_thisyr", "lung_med1", "lung_med1m4h", "lung_med1m8h", "lung_med2m4h", "lung_med2m8h", "lung_med2type", "lung_med3m4h", "lung_med3m8h", "lung_med3type", "lung_med4m4h", "lung_med4m8h", "lung_med4type", "lung_med5m4h", "lung_med5m8h", "lung_med5type", "special_work", "education_level", "farm_child", "farm_child_goat", "farm_child_dairy", "farm_child_veal", "farm_child_sheep", "farm_child_pig", "farm_child_poultry", "farm_child_horse", "farm_child_agri", "farm_child_other", "health_complaint_farm_rel", "covid19_infection", "home_goatfarm", "farm_work_feeding", "farm_work_milking", "farm_work_cleanstables", "farm_work_litter", "farm_work_manure", "farm_work_yean", "farm_work_newborn", "farm_work_cleaning", "farm_work_soil", "farm_work_other", "other_work")

variables_to_factor <- c(variables_to_factor_part1, variables_to_factor_part2)

# Check which variables are in 'meta'
valid_variables <- variables_to_factor %in% colnames(metadata)
if (!all(valid_variables)) {
  warning("The following variables are not in 'meta': ", 
          paste(variables_to_factor[!valid_variables], collapse = ", "))
}

# Convert to factor variables
metadata[variables_to_factor] <- lapply(metadata[variables_to_factor], factor)

sum(metadata$population=="CP") # n = 1814 total samples for CP
sum(metadata$population=="GF") # n = 175 total samples for CP

write.csv(metadata,"../Output/Participant_descriptives/VGO3_population_data.csv")

# Each participant has 1 or more samples (NP and OP samples mostly for all)
# VGO study number for the controls and goat farmers is in the column 'VGO3_ID' - Only keep unique IDs
metadata_uniq <- metadata %>%
  distinct(VGO3_ID, .keep_all = TRUE) 

# Remove rows which are blanks 
metadata_uniq <- metadata_uniq[!is.na(metadata_uniq$population), ] # 1172 left

metadata_uniq$X <- NULL

sum(metadata_uniq$population=="CP") # n = 963
sum(metadata_uniq$population=="GF") # n = 96

write.csv(metadata_uniq,"../Output/Participant_descriptives/VGO3_population_data_included_16S.csv" ) # 1172 samples
```


<!-- # Data adjustments -->
<!-- ```{r} -->
<!-- # Extract metadata -->
<!-- meta <- read.csv("../Output/Metadata/VGO3_metadata_all_livestock_nodups.csv") -->

<!-- # Many of the variables are imported as integer variables when they should actually be character variables -->
<!-- variables_to_factor_part1 <- c("gender", "abroad_lastmth", "animal_contact_lastmth", "cat_contact_lastmth", "dog_contact_lastmth", "rodent_contact_lastmth", "bird_contact_lastmth", "chicken_contact_lastmth", "sheep_contact_lastmth", "cow_contact_lastmth", "pig_contact_lastmth", "horse_contact_lastmth", "pneumonia_lastyr", "acute_resp_infec_lastyr", "covid19", "covid19_vaccine", "antibiotics_lastyr", "antacids_lastyr", "lung_med", "lung_med1_type", "lung_med1_more4hrs", "lung_med1_more8hrs", "lung_med2_type", "lung_med2_more4hrs", "lung_med2_more8hrs", "lung_med3_type", "lung_med3_more4hrs", "lung_med3_more8hrs", "lung_med4_type", "lung_med4_more4hrs", "lung_med4_more8hrs", "lung_med5_type", "lung_med5_more4hrs", "lung_med5_more8hrs", "beta_blockers", "heart_failure_attack_3m", "chest_abdom_surg_3m", "aortic_aneurysm", "cough_blood", "eye_ear_brain_surg_lastmth", "imm_def_med_current", "imm_def_illness_current", "preg_last_trimester", "lungfunc_discom", "breathalyser_diff", "consent", "onlquest_done", "fieldquest_done", "spirometry_done", "serum_done", "OP_blank_done", "NP_blank_done", "NP_blank_ID", "NP_swab_done", "work_less_19hrs", "work_more_19hrs", "manage_house", "unemployed", "student", "disabled", "retired", "voluntarywork", "health_status", "heart_vascu_disorder", "imm_def_illness", "imm_def_med", "diabetes", "wheezing_lastyr", "wheezing_SOB", "wheezing_not_cold", "tight_chest_lastyr", "SOB_lastyr", "cough_lastyr", "SOB_rest_lastyr", "nasal_allergy", "nasal_allergy_Jan", "nasal_allergy_Feb", "nasal_allergy_Mar", "nasal_allergy_Apr", "nasal_allergy_May", "nasal_allergy_Jun", "nasal_allergy_Jul", "nasal_allergy_Aug", "nasal_allergy_Sep", "nasal_allergy_Oct", "nasal_allergy_Nov", "nasal_allergy_Dec", "asthma_ever", "asthma_diag", "asthma_Jan_Feb", "asthma_Mar_Apr", "asthma_May_Jun", "asthma_Jul_Aug", "asthma_Sep_Oct", "asthma_Nov_Dec", "asthma_att_lastyr", "asthma_med", "cough_daily_3mperyr", "phlegm_daily_3mperyr", "COPD_emphysema_diag", "EAA_diag", "cort_inhaler_lastyr", "pneumonia_last3yr", "pneumonia_GP_diag", "pneumonia_antibiotics") -->
<!-- variables_to_factor_part2 <- c("pneumonia_specialist", "pneumonia_specialist_conf", "pneumonia_chest_photo", "pneumonia_conf_photo", "pneumonia_specialist_antibiotics", "pneumonia_hosp", "pneumonia_fever", "pneumonia_dyspnea", "pneumonia_cough", "pneumonia_muscle_pain", "pneumonia_chest_pain", "pneumonia_wheezing", "pneumonia_stomach_pain", "pneumonia_fatigue", "pneumonia_depressed", "flu_vacc", "flu_vacc_duration", "pneumococcal_vacc", "antibiotics_lastyr_oqdata", "antibiotic_month_oqdata", "antibiotic_year_oqdata", "last_antibiotic_used", "covid19_close_contact", "covid19_household", "home_type", "move_plans", "move_no_reason", "move_health", "move_job", "move_house", "move_env", "pets_last5yrs", "cat_last5yrs", "dog_last5yrs", "bird_last5yrs", "small_animals_last5yrs", "rodent_last5yrs", "fish_last5yrs", "turtle_last5yrs", "farmanim_hobby_last5yrs", "pig_last5yrs", "cow_last5yrs", "sheep_last5yrs", "goat_last5yrs", "poultry_last5yrs", "horse_last5yrs", "no_farm_visit_lastyr", "family_farm_visit_lastyr", "job_farm_visit_lastyr", "buy_farm_visit_lastyr", "petting_zoo_visit_lastyr", "other_reason_farm_visit_lastyr", "smoked_ever", "smoke_exp_indoor_freq", "symptom_other", "CRP_test_done", "Saturation_test_done", "lung_disease", "COPD_status", "imm_def", "lung_inhal_med", "antibiotics_lastmth", "dyspnea", "cough", "hypotension", "fever", "pain_breathing", "tachycardia", "tachypnea", "confusion", "lung_med1type", "goat_contact_lastmth", "health_remarks", "lambs_thisyr", "lung_med1", "lung_med1m4h", "lung_med1m8h", "lung_med2m4h", "lung_med2m8h", "lung_med2type", "lung_med3m4h", "lung_med3m8h", "lung_med3type", "lung_med4m4h", "lung_med4m8h", "lung_med4type", "lung_med5m4h", "lung_med5m8h", "lung_med5type", "special_work", "education_level", "farm_child", "farm_child_goat", "farm_child_dairy", "farm_child_veal", "farm_child_sheep", "farm_child_pig", "farm_child_poultry", "farm_child_horse", "farm_child_agri", "farm_child_other", "health_complaint_farm_rel", "covid19_infection", "home_goatfarm", "farm_work_feeding", "farm_work_milking", "farm_work_cleanstables", "farm_work_litter", "farm_work_manure", "farm_work_yean", "farm_work_newborn", "farm_work_cleaning", "farm_work_soil", "farm_work_other", "other_work","GoatFarmExposureCategory", "ChickenFarm1000m", "ChickenFarm2000m") -->

<!-- variables_to_factor <- c(variables_to_factor_part1, variables_to_factor_part2) -->

<!-- # Check which variables are in 'meta' -->
<!-- valid_variables <- variables_to_factor %in% colnames(meta) -->
<!-- if (!all(valid_variables)) { -->
<!--   warning("The following variables are not in 'meta': ",  -->
<!--           paste(variables_to_factor[!valid_variables], collapse = ", ")) -->
<!-- } -->

<!-- # Convert to factor variables -->
<!-- meta[variables_to_factor] <- lapply(K[variables_to_factor], factor) -->

<!-- sum(meta$population=="CP") # n = 969 -->
<!-- sum(meta$population=="GP") # n = 108 -->
<!-- sum(meta$population=="GF") # n = 100 -->

<!-- write.csv(meta,"../Output/Participant_descriptives/VGO3_population_data.csv") -->
<!-- ``` -->
<!-- # Only participants with at least 1 OP or NP sample sequenced -->
<!-- ```{r} -->
<!-- # Each participant has 1 or more samples (NP and OP samples mostly for all) -->
<!-- # VGO study number for the controls and goat farmers is in the column 'VGO3_ID'  -->
<!-- # Only keep unique IDs -->
<!-- meta_16S <- read.csv("../Output/Metadata/VGO3_metadata_all_livestock_16Slab.csv") -->

<!-- meta_uniq_16S <- meta_16S %>% -->
<!--   distinct(VGO3_ID, .keep_all = TRUE)  -->

<!-- # Remove rows which are blanks  -->
<!-- meta_uniq_16S_noblanks <- meta_uniq_16S[!is.na(meta_uniq_16S$population), ] # 1172 left -->

<!-- meta_uniq_16S_noblanks$X <- NULL -->

<!-- # ps_complete <- readRDS("../Output/Phyloseq/ps_complete.Rds") -->
<!-- # meta_uniq_16S_noblanksps <- meta_uniq_16S_noblanks[meta_uniq_16S_noblanks$VGO3_ID %in% ps_complete@sam_data$VGO3_ID, ] # Still 1170 remaining -->

<!-- sum(meta_uniq_16S_noblanks$population=="CP") # n = 967 -->
<!-- sum(meta_uniq_16S_noblanks$population=="GP") # n = 108 -->
<!-- sum(meta_uniq_16S_noblanks$population=="GF") # n = 97 -->

<!-- write.csv(meta_uniq_16S_noblanks,"../Output/Participant_descriptives/VGO3_population_data_included_16S.csv" ) # 1172 samples -->
<!-- ``` -->
<!-- Check which IDs are different -->
<!-- ```{r} -->
<!-- # Find VGO3_ID values in meta_uniq_16S_noblanks but not in ps_complete@sam_data -->
<!-- unique_in_meta16S <- setdiff(meta_uniq_16S_noblanks$VGO3_ID, meta$VGO3_ID) -->

<!-- # Find VGO3_ID values in ps_complete@sam_data but not in meta_uniq_16S_noblanks -->
<!-- unique_in_meta <- setdiff(meta$VGO3_ID, meta_uniq_16S_noblanks$VGO3_ID) -->

<!-- # Display the discrepancies -->
<!-- cat("VGO3_IDs in meta_uniq_16S_noblanks but not in meta:\n") -->
<!-- print(unique_in_meta16S) -->

<!-- cat("\nVGO3_IDs in meta but not in meta_uniq_16S_noblanks:\n") -->
<!-- print(unique_in_meta) # 17508 29798 40053 40155 40194 Possibly these were not sequenced for whatever reason -->

<!-- ``` -->

# Table1
```{r}
metadata_uniq$gender <- 
  factor(metadata_uniq$gender, levels=c(0,1),
         labels=c("Male", 
                  "Female"))
metadata_uniq$smoked_ever <- 
  factor(metadata_uniq$smoked_ever, levels=c(0,1,2),
         labels=c("No", 
                  "Ex-smoker",
                  "Smoker"))
metadata_uniq$asthma_ever <- 
  factor(metadata_uniq$asthma_ever, levels=c(0,1),
         labels=c("No", 
                  "Yes"))
metadata_uniq$COPD_emphysema_diag <- # N.B for CP and GF this diagnosis is COPD & emphysema but for GPs it is just COPD
  factor(metadata_uniq$COPD_emphysema_diag, levels=c(0,1),
         labels=c("No", 
                  "Yes"))
metadata_uniq$lung_med <- 
  factor(metadata_uniq$lung_med, levels=c(0,1),
         labels=c("No", 
                  "Yes"))
metadata_uniq$imm_def <- 
  factor(metadata_uniq$imm_def, levels=c(0,1),
         labels=c("No", 
                  "Yes"))
metadata_uniq$flu_vacc <- 
  factor(metadata_uniq$flu_vacc, levels=c(0,1),
         labels=c("No", 
                  "Yes"))
metadata_uniq$pneumococcal_vacc <- 
  factor(metadata_uniq$pneumococcal_vacc, levels=c(0,1),
         labels=c("No", 
                  "Yes"))
metadata_uniq$antibiotics_lastyr <- # for CP and GF
  factor(metadata_uniq$antibiotics_lastyr, levels=c(0,1),
         labels=c("No", 
                  "Yes"))
metadata_uniq$antibiotics_lastmth <- # for GP
  factor(metadata_uniq$antibiotics_lastmth, levels=c(0,1),
         labels=c("No", 
                  "Yes"))
metadata_uniq$abroad_lastmth<- 
  factor(metadata_uniq$abroad_lastmth, levels=c(0,1),
         labels=c("No", 
                  "Yes"))
metadata_uniq$animal_contact_lastmth<- 
  factor(metadata_uniq$animal_contact_lastmth, levels=c(0,1),
         labels=c("No", 
                  "Yes"))

label(metadata_uniq$sampling_season) <- "Sampling season"
label(metadata_uniq$age) <- "Age"
label(metadata_uniq$gender) <- "Gender"
label(metadata_uniq$smoked_ever) <- "Smoking status"
label(metadata_uniq$asthma_ever) <- "Asthma (ever)"
label(metadata_uniq$COPD_emphysema_diag) <- "COPD/emphysema"
label(metadata_uniq$lung_med) <- "Lung medication used"
label(metadata_uniq$imm_def) <- "Immunocompromised"
label(metadata_uniq$flu_vacc) <- "Influenza vaccination"
label(metadata_uniq$pneumococcal_vacc) <- "Pneumococcal vaccination"
label(metadata_uniq$animal_contact_lastmth) <- "Animal contact in the last month"
label(metadata_uniq$abroad_lastmth) <- "Abroad in the last month"
label(metadata_uniq$KRD_nCowsWghtDist.3000m.sum) <- "Number of distance weighted cows in 3km"
label(metadata_uniq$KRD_nGoatsWghtDist.3000m.sum) <- "Number of distance weighted goats in 3km"
label(metadata_uniq$KRD_nPigsWghtDist.3000m.sum) <- "Number of distance weighted pigs in 3km"
label(metadata_uniq$KRD_nPoultryWghtDist.3000m.sum) <- "Number of distance weighted chickens in 3km"


pvalue <- function(x, ...) {
  # Construct vectors of data y, and groups (strata) g
  y <- unlist(x)
  g <- factor(rep(1:length(x), times = sapply(x, length)))
  
  if (is.numeric(y)) {
    # For numeric variables, perform ANOVA
    p <- anova(lm(y ~ g))$"Pr(>F)"[1]
  } else {
    # For categorical variables
    tbl <- table(y, g)
    
    # Check if any cell in the contingency table is 0
    if (any(tbl == 0)) {
      # If any cell in the contingency table is 0, perform Fisher's exact test
      p <- tryCatch({
        fisher.test(tbl, workspace = 2e9)$p.value  # Increase workspace size
      }, error = function(e) {
        NA  # Handle errors due to large contingency tables
      })
    } else {
      # Otherwise, perform chi-squared test
      p <- chisq.test(tbl)$p.value
    }
  }
  
  # Format the p-value, using an HTML entity for the less-than sign.
  # The initial empty string places the output on the line below the variable label.
  c("", sub("<", "&lt;", format.pval(p, digits = 3, eps = 0.001)))
}

All_populations_stats <- table1(
  ~ sampling_season + age + gender + smoked_ever + asthma_ever + COPD_emphysema_diag + lung_med + imm_def + flu_vacc + pneumococcal_vacc + animal_contact_lastmth + abroad_lastmth | population,
  data = metadata_uniq,
  overall=F, 
  extra.col=list(`P-value`=pvalue))


write.csv(All_populations_stats, file = "../Output/Participant_descriptives/All_populations_manuscript_table1.csv")



# Livestock exposures for the CP only
# Filter for the CP population
metadata_cp <- metadata_uniq[metadata_uniq$population == "CP", ]

# Define the variables you want to update
variables_to_update <- c("KRD_nCowsWghtDist.3000m.sum", 
                         "KRD_nGoatsWghtDist.3000m.sum", 
                         "KRD_nPigsWghtDist.3000m.sum", 
                         "KRD_nPoultryWghtDist.3000m.sum")

# Replace NA with 0 for rows where population is "CP"
for (var in variables_to_update) {
  metadata_cp[[var]][metadata_cp$population == "CP" & is.na(metadata_cp[[var]])] <- 0
}


# Generate the summary table for CP only
CP_livestock_summary <- table1(
  ~ ecoli_RF_preds + staph_RF_preds +
    tetw_RF_preds + meca_RF_preds + KRD_nCowsWghtDist.3000m.sum + KRD_nGoatsWghtDist.3000m.sum +
    KRD_nPigsWghtDist.3000m.sum + KRD_nPoultryWghtDist.3000m.sum,
  data = metadata_cp,
  overall = TRUE
)

# Print the table
CP_livestock_summary
write.csv(CP_livestock_summary, file = "../Output/Participant_descriptives/CP_livestock_summary_table1.csv")
```

# Explore distribution of livestock exposures 
```{r}
library(ggplot2)
library(tidyr)

# Create a long-format dataset for easier visualization
livestock_long <- metadata_cp %>%
  select(ecoli_RF_preds, staph_RF_preds, tetw_RF_preds, meca_RF_preds, 
         KRD_nCowsWghtDist.3000m.sum, KRD_nGoatsWghtDist.3000m.sum, 
         KRD_nPigsWghtDist.3000m.sum, KRD_nPoultryWghtDist.3000m.sum) %>%
  pivot_longer(cols = everything(), names_to = "Variable", values_to = "Value")

# Histogram for all variables
distribution_livestock <- ggplot(livestock_long, aes(x = Value)) +
  geom_histogram(binwidth = 0.1, fill = "blue", color = "black", alpha = 0.7) +
  facet_wrap(~ Variable, scales = "free") +
  labs(title = "Distribution of Livestock Variables", x = "Value", y = "Frequency") +
  theme_minimal()


ggsave("../Output/Participant_descriptives/Livestock_var_distribution.svg",  distribution_livestock)

library(psych)

# Summarize livestock variables
summary_stats <- describe(metadata_cp %>%
                            select(ecoli_RF_preds, staph_RF_preds, tetw_RF_preds, meca_RF_preds, 
                                   KRD_nCowsWghtDist.3000m.sum, KRD_nGoatsWghtDist.3000m.sum, 
                                   KRD_nPigsWghtDist.3000m.sum, KRD_nPoultryWghtDist.3000m.sum))
print(summary_stats)
summary_stats <- describe(metadata_cp %>%
                            select(
                                   KRD_nCowsWghtDist.3000m.sum, KRD_nGoatsWghtDist.3000m.sum, 
                                   KRD_nPigsWghtDist.3000m.sum, KRD_nPoultryWghtDist.3000m.sum))

# RF-modelled agents appear normally distributed - can use as continuous in analyses 
# distance-weighted animal variables are highly skewed, try separating into tertiles and compare T1 vs T3

sum(metadata_cp$KRD_nCowsWghtDist.3000m.sum == 0)#0 
sum(metadata_cp$KRD_nGoatsWghtDist.3000m.sum == 0)#162
sum(metadata_cp$KRD_nPigsWghtDist.3000m.sum == 0)#0 
sum(metadata_cp$KRD_nPoultryWghtDist.3000m.sum == 0)#11 



metadata_cp$sqrt_KRD_nGoats <- sqrt(metadata_cp$KRD_nGoatsWghtDist.3000m.sum + 1)
metadata_cp$log_KRD_nGoats <- log(metadata_cp$KRD_nGoatsWghtDist.3000m.sum + 1)

hist(metadata_cp$sqrt_KRD_nGoats)
hist(metadata_cp$log_KRD_nGoats)

metadata_cp$sqrt_KRD_ncows <- sqrt(metadata_cp$KRD_nCowsWghtDist.3000m.sum + 1)
metadata_cp$log_KRD_ncows <- log(metadata_cp$KRD_nCowsWghtDist.3000m.sum + 1)

hist(metadata_cp$sqrt_KRD_ncows)
hist(metadata_cp$log_KRD_ncows)




cor(metadata_cp$Shannon, metadata_cp$KRD_nCowsWghtDist.3000m.sum)


# Scatter plot to visualize the relationship
plot(metadata_cp$KRD_nCowsWghtDist.3000m.sum, metadata_cp$Shannon,
     xlab = "KRD_nCowsWghtDist.3000m.sum", ylab = "Shannon Diversity",
     main = "Scatter plot of Shannon Diversity vs. Cattle Distance")


plot(metadata_cp$log_KRD_ncows, metadata_cp$Shannon,
     xlab = "KRD_nCowsWghtDist.3000m.sum", ylab = "Shannon Diversity",
     main = "Scatter plot of Shannon Diversity vs. Cattle Distance")

# Apply the log transformation to the KRD_nCowsWghtDist.3000m.sum variable

# Fit the linear regression model using the transformed variable
lm_cattle_log <- lm(Shannon ~ log_KRD_ncows + age + sampling_season + gender + smoked_ever, data = metadata_cp)

# Summarize the results
summary(lm_cattle_log)

# Check residuals for the fit
plot(lm_cattle_log, which = 1)  # Residuals vs Fitted values



```



